# Generated by Django 6.0.3 on 2026-07-21 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='tiemstamp',
            new_name='timestamp',
        ),
    ]
