# Generated by Django 6.0.3 on 2026-08-13 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('paternal_name', models.CharField(max_length=100)),
                ('maternal_name', models.CharField(blank=True, max_length=100)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('gender', models.CharField(choices=[('female', 'Femenino'), ('male', 'Masculino'), ('other', 'Otro')], max_length=10)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
